export const chains = [
  {
    id: 1,
    name: 'Binance',
    chainId: 56,
    shortName: 'BNB',
    chain: 'BNB',
    network: 'mainnet',
    networkId: 56,
    icon: '/images/home2.0/coin-icons/bnb.svg',
  },
  {
    id: 2,
    name: 'Ethereum',
    chainId: 1,
    shortName: 'ETH',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 1,
    icon: '/images/home2.0/purple-ethereum.svg',
  },

  {
    id: 3,
    name: 'Roburna',
    chainId: 156,
    shortName: 'RBA',
    chain: 'RBA',
    network: 'mainnet',
    networkId: 156,
    icon: '/images/home2.0/roburna-blockchain.svg',
  },
  {
    id: 2,
    name: 'Solana',
    chainId: 101,
    shortName: 'SOL',
    chain: 'SOL',
    network: 'mainnet',
    networkId: 101,
    icon: '/images/home2.0/solana.svg',
  },
]
